name: Code Quality Check & Auto-Fix

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-fix:
    name: Code Quality Fixes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort autopep8 flake8 pre-commit

      - name: Run Black (Auto-Fix)
        run: |
          black .
          git add .
      
      - name: Run isort (Auto-Fix)
        run: |
          isort .
          git add .

      - name: Run autopep8 (Auto-Fix)
        run: |
          autopep8 --in-place --recursive .
          git add .

      - name: Run Flake8 (Check for Errors)
        run: |
          flake8 || true  # Allow warnings but don't fail CI

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "🔧 Auto-fixed code formatting & linting issues" || echo "No changes to commit"
          git push || echo "No changes to push"
